name: сборка релиза
run-name: ${{ github.actor }} запустил сборку релиза при пуше тега
on: 
  push:
    tags:
      - 'rc-0.0.[0-9]+'
jobs:
  check-ts-and-lint:
    name: запуск ts и lint
    uses: ./.github/workflows/check-ts-and-lint.yml
  
  build:
    name: сборка релиза
    needs: check-ts-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: копируем репозиторий
        uses: actions/checkout@v3
      
      - name: устанавливаем Node.js 16.6.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.6.0'
          
      - name: устанавливаем npm пакеты
        run: npm ci
      
      - name: собираем приложение
        run: npm run build
        
      - name: запускаем тесты
        run: npm run test

      - name: заполняем релизный тикет
        uses: molodaneporochnacubinka/fill-ticket-action@v1.9
        with:
          token: ${{ secrets.OAUTH_TRACKER_TOKEN }}
          x-org-id: 7526988
          ticket-id: HOMEWORKSHRI-147
          tag: ${{ github.ref_name }}

      - name: собираем докер образ проекта
        run: |
          docker build . -t $IMAGE
        env:
          IMAGE: ${{ github.ref_name }}

      - name: прикрепляем тег образа в комментарий релизного тикета
        uses: molodaneporochnacubinka/add-comment-action@v1.1
        with:
          token: ${{ secrets.OAUTH_TRACKER_TOKEN }}
          x-org-id: 7526988
          ticket-id: HOMEWORKSHRI-147
          comment: Собрали образ с тегом ${{ github.ref_name }}

